apiVersion: apps/v1
kind: Deployment
metadata:
  name: stakeway-test
  labels:
    app: stakeway-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stakeway-test
  template:
    metadata:
      labels:
        app: stakeway-test
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8000"
    spec:
      containers:
      - name: stakeway-test
        image: devking0718/stakeway-test:latest
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: stakeway-test-config
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5 