apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-alerts
data:
  alerts.yml: |
    groups:
    - name: stakeway-test-alerts
      rules:
      - alert: ServiceDown
        expr: up{job="stakeway-test"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Stakeway Test service is down"
          description: "Stakeway Test service has been down for more than 1 minute"
      
      - alert: HighLatency
        expr: rate(http_request_duration_seconds_sum[5m]) / rate(http_request_duration_seconds_count[5m]) > 0.5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High latency detected"
          description: "Average response time is above 500ms for the last 5 minutes" 